---
- name: ansible directory
  file: path=/usr/local/etc/ansible
    owner=ansible
    group=ansible
    mode=0770
    state=directory
    recurse=yes

- name: latest ansible source
  git: dest=/home/matt/source-ansible
    repo=https://github.com/ansible/ansible
    recursive=yes
  
- name: my ansible files
  git: repo=https://github.com/mwpher/ansible-stuff
    dest=/home/matt/ansible-stuff
    recursive=yes
    track_submodules=yes

- name: install pip
  pkgng: name=py27-pip state=present

- name: ansible dependencies
  pip: name={{ item }} state=present
  with_items:
  - paramiko
  - PyYAML
  - Jinja2
  - httplib2
