---
- name: ansible directory
  file: path=/etc/ansible
    owner=ansible
    group=ansible
    mode=0770
    state=directory

- name: install pip
  pkgng: name=py27-pip state=present
  tags:
  - packages
- name: install ansible
  pip: name=ansible state=latest
  tags:
  - packages

- name: my ansible files
  sudo_user: matt
  git: repo=https://github.com/mwpher/ansible-stuff
    dest=/home/matt/ansible-stuff
    recursive=yes
    force=no
  ignore_errors: yes
  tags:
  - git
