---
- name: add my site git
  git: repo=https://github.com/mwpher/Pico
    dest=/usr/local/www/pico

- name: set permissions
  file: path=/usr/local/www/pico/
    owner=www
    group=www
    mode=0755
    state=directory

- name: pico fastcgi
  template: src=pico.conf
    dest=/usr/local/etc/php-fpm.d/pico.conf
    owner=root
    group=wheel
    mode=0644
  notify: restart php-fpm

- name: add pico vhost
  template: src=pico
    dest=/usr/local/etc/nginx/sites-available/pico
    owner=root
    group=wheel
    mode=0644
  notify: restart nginx

- name: enable pico vhost
  file: src=/usr/local/etc/nginx/sites-available/pico
    dest=/usr/local/etc/nginx/sites-enabled/pico
    state=link
  notify: restart nginx
