---
- name: dotfiles git
  sudo_user: matt
  git: repo=https://github.com/mwpher/dotfiles
    dest=/home/matt/dotfiles
    recursive=yes
    track_submodules=yes
    force=no
  ignore_errors: yes
  tags:
  - git

- name: set up git correctly
  sudo_user: matt
  shell: "{{ item }}"
  with_items:
  - git config --global user.name "Matthew Pherigo"
  - git config --global user.email hybrid120@gmail.com
  - git config --global push.default simple
  tags:
  - git

- name: link dotvim
  sudo_user: matt
  file: src=/home/matt/dotfiles/dotvim dest=/home/matt/.vim state=link
- name: link zshrc
  sudo_user: matt
  file: src=/home/matt/dotfiles/zshrc dest=/home/matt/.zshrc state=link
- name: link tmux.conf
  sudo_user: matt
  file: src=/home/matt/dotfiles/tmux.conf dest=/home/matt/.tmux.conf state=link
