---
- name: install FreeBSD stuff
  pkgng: name={{ item }} state=present
  with_items:
    - git
    - sudo
    - vim-lite
    - zsh
    - bash
    - tmux
  tags:
  - packages

- name: FreeBSD easy-sudoers
  template: src=/home/matt/dotfiles/easy-sudoers.j2
    dest=/usr/local/etc/sudoers.conf
    validate='visudo -cf %s'

#  - name: install & setup denyhosts
#    pkgng: name=denyhosts state=present
#    template: src=/home/matt/dotfiles/denyhosts/denyhosts.conf dest=/usr/local/etc/denyhosts.conf    
#    when: ansible_os_family == "FreeBSD"
#    tags: denyhosts
