---
- name: install FreeBSD stuff
  pkgng: name={{ item }} state=present cached=yes
  with_items:
    - git
    - vim-lite
    - zsh
    - bash
    - tmux
  tags:
  - packages

#  - name: install & setup denyhosts
#    pkgng: name=denyhosts state=present
#    template: src=/home/matt/dotfiles/denyhosts/denyhosts.conf dest=/usr/local/etc/denyhosts.conf    
#    when: ansible_os_family == "FreeBSD"
#    tags: denyhosts
