---
- name: install stuff
  openbsd_pkg: name={{ item }} state=present
  with_items:
    - git
    - vim
    - zsh
    - bash
    - sshguard--
  tags:
  - packages

- name: OpenBSD easy-sudoers
  template: src=/home/matt/dotfiles/OpenBSD/sudoers
    dest=/etc/sudoers
    validate='visudo -cf %s'
