---
- hosts: all
  remote_user: root
  accelerate: false
  pre_tasks:

  - name: SSL cert package
    pkgng: name=ca_root_nss state=present
    when: ansible_distribution == 'FreeBSD'

  - name: ansible group
    group: name=ansible state=present

  - name: add ansible user
    action: user name=ansible 
      shell=/bin/sh 
      group=ansible 
      groups=wheel 
      append=yes
  
  - name: upload ansible key
    authorized_key: user=ansible
      key="{{ lookup('file', '/home/matt/.ssh/ansible_rsa.pub') }}"
    #"

  - name: add dependencies for accelerated mode
    pkgng: name={{ item }} state=present
    with_items:
    - py27-asn1
    - py27-keyczar

  roles:
  - { role: sshd }
