---
- hosts: all
  sudo: yes
  #accelerate: yes

  pre_tasks:
  - group_by: key={{ansible_distribution}}
  roles:
  - { role: sshd, tags: 'sshd,base' }
  - { role: common, tags: 'common,base' }

- hosts: my_profile
  sudo: yes

  pre_tasks:
  - group_by: key={{ansible_distribution}}
  roles:
  - { role: matt, tags: 'matt' }

- hosts: ZFS
  sudo: yes

  pre_tasks:
  - group_by: key={{ansible_distribution}}
  roles:
  - { role: zfs_auto_snapshot, tags: 'base' }

- hosts: Chiyochan.home
  sudo: yes

  pre_tasks:
  - group_by: key={{ansible_distribution}}
  roles:
  - { role: ansible_control, tags: 'base' }
  - { role: matt_programming, tags: 'matt' }

- hosts: pico
  sudo: yes
  vars:
    nginx: True
    phpfpm: True
  pre_tasks:
  - group_by: key={{ansible_distribution}}
  roles:
  - { role: pico, tags: 'www,pico' }
