---
- hosts: all
  sudo: yes
  #  accelerate: yes

  pre_tasks:
  - group_by: key={{ansible_distribution}}
  roles:
  - { role: sshd, tags: 'base' }
  tasks:
  - include: roles/installme/tasks/rsync.yml tags=base

- hosts: workstation
  sudo: yes
  pre_tasks:
  - group_by: key={{ansible_distribution}}
  roles:
  - { role: matt, tags: 'matt' }
  - { role: sshd, tags: 'base' }

- hosts: ansible_host
  sudo: yes
  pre_tasks:
  - group_by: key={{ansible_distribution}}
  roles:
  - { role: ansible_control, tags: 'base' }

- hosts: ZFS
  sudo: yes
  pre_tasks:
  - group_by: key={{ansible_distribution}}
  roles:
  - { role: zfs_auto_snapshot, tags: 'base' }
