---
- hosts: all
  sudo: yes
  #  accelerate: yes

  pre_tasks:
  - group_by: key={{ansible_distribution}}
  tasks:
  - include: roles/installme/tasks/rsync.yml

- hosts: workstation
  sudo: yes
  #  accelerate: yes
  roles:
  - matt
  - sshd

- hosts: ansible_host
  sudo: yes
  roles:
  - ansible_control

- hosts: ZFS
  sudo: yes
  #  accelerate: yes
  roles:
  - zfs_auto_snapshot
