---
- hosts: all
  sudo: yes
  accelerate: yes

  pre_tasks:
  - group_by: key={{ansible_distribution}}

- hosts: workstation
  sudo: yes
  accelerate: yes
  roles:
  - matt
  - sshd

- hosts: FreeBSD
  sudo: yes
  accelerate: yes
  roles:
  - zfs_auto_snapshot
