---
- hosts: all
  sudo: yes
  #accelerate: yes

  pre_tasks:
  - group_by: key={{ansible_distribution}}
  roles:
  - { role: common, tags: 'common,base' }
  - { role: bacula, tags: "common,base,packages,bacula", when: bacula is defined }
  - { role: matt, tags: 'matt', when: my_profile }
  - { role: zfs_auto_snapshot, tags: 'base', when: ZFS }
  - { role: ansible_control, tags: 'base', when: ansible_control }
  - { role: www_home, tags: 'www,www_home', when: www_home }
  - { role: jailhost, tags: 'ezjail,jails,www', when: jailhost }

- hosts: www
  sudo: yes
  #accelerate: yes

  pre_tasks:
  - group_by: key={{ansible_distribution}}
  roles:
  - { role: pico, tags: 'www,pico', when: pico }
  #  - { role: ANXS-postgresql, 
  #    postgresql_databases: [ { name: 'gitlabhq_production' } ],
  #    postgresql_users: [ { name: 'git', db: 'gitlabhq_production' }, { name: 'test', db: 'test' } ],
  #    tags: ['www', 'db'],
  #    when: postgresql }
