---
- hosts: all
  remote_user: ansible
  sudo: yes
  accelerate: true

  pre_tasks:
  - group_by: key={{ansible_distribution}}

- hosts: workstation
  remote_user: ansible
  sudo: yes
  roles:
  - matt
  - sshd
