---
- hosts: openbsd
  user: ansible
  sudo: yes

  tasks:
  - name: install stuff
    openbsd_pkg: name={{ item }} state=present
    with_items:
      - git
      - vim
      - zsh
      - bash
      - sshguard--

  - name: lol
    command: echo 'ping!'
