---
# common/defaults/main.yml
git: True
postfix: False

openntpd: False
ntpd_server: "pool.ntp.org"

pf: False

logwatch: "YES"
logwatch_hour: 8

periodic_user: matt
daily_clean_tmps_enable: True

sshguard: "YES"
sshguard_watch_logs: "/var/log/auth.log" # colon-seperated

syslogd_flags: "-ss -c"

# Sample PF:
# pf:
#   ext:
#     if: "vtnet0"
#     addr: "8.8.8.8"
#   priv:
#     if: "vtnet1"
#     addr: "192.168.1.1"
#
# Sample jailhost entry:
# jailhost:
#   if: "lo1"
#   jails:
#   - name: "www"
#     ip: "10.0.0.1"
#     rdr:
#       port: 80
#       port_ext: 8080
