---
# common/defaults/main.yml
git: True
postfix: False

openntpd: False
ntpd_server: "pool.ntp.org"

logwatch: "YES"
logwatch_hour: 8

periodic_user: matt
daily_clean_tmps_enable: True

sshguard: "YES"
sshguard_watch_logs: "/var/log/auth.log" # colon-seperated

syslogd_flags: "-ss -c"
