---
- name: restart network
  raw: /etc/netstart
- name: restart ezjail
  service: name=ezjail state=restarted
- name: restart sshd
  service: name=sshd state=restarted
- name: restart ntpd
  service: name=ntpd state=restarted
