---
- name: restart sshguard
  service: name=sshguard state=restarted

- name: restart syslogd
  service: name=syslogd state=restarted

- name: update aliases
  command: newaliases

- name: restart openntpd
  service: name=openntpd state=restarted

- name: restart pf
  service: name=pf state=restarted
- name: reload pf
  command: pfctl -vf /etc/pf.conf

- name: set time
  command: ntpdate {{ ntpd_server }}
