---
sshd_port: 22
sshd_permit_root_login: 'without-password'
#sshd_listen_addresses: []
sshd_password_authentication: 'no'
sshd_tcp_forwarding: 'yes'
sshd_x11_forwarding: 'no'
ssh_verifyDNS: 'yes'
ssh_StrictHostKeyChecking: 'ask'

ssh_portable: false
ssh_conf: '/etc/ssh'
ssh_service: 'sshd'
