---
- include: logwatch.yml
  when: logwatch == "YES"

- include: sshguard.yml
  when: sshguard == "YES"

- name: git package
  pkgng: name=git state=present
  when: git == True

- include: periodic.yml 

- include: rcconf.yml
