---
- include: rcconf.yml

- name: syslogd flags
  sysrc: key="syslogd_flags" value="{{ syslogd_flags }}"
    state="present"
  notify: restart syslogd

- include: openntpd.yml tags='common,base,openntpd'
  when: openntpd

- include: pf.yml tags='common,base,pf'
  when: pf

- include: logwatch.yml tags='common,base,logwatch'
  when: logwatch == "YES"

- include: sshguard.yml tags='common,base,sshguard,ssh'
  when: sshguard == "YES"

- name: git package
  pkgng: name=git state=present cached=yes
  when: git == True
  tags:
  - packages

- name: bsdstats
  pkgng: name=bsdstats state=present
  tags:
  - packages

- include: periodic.yml tags='common,base,freebsd,periodic'

- include: postfix.yml tags='common,base,mail,postfix'
  when: postfix == True
