---
- include: logwatch.yml
  when: logwatch == "YES"

- include: sshguard.yml
  when: sshguard == "YES"

- name: git package
  pkgng: name=git state=present cached=yes
  when: git == True
  tags:
  - packages

- name: bsdstats
  pkgng: name=bsdstats state=present cached=yes
  tags:
  - packages

- include: periodic.yml 

- include: rcconf.yml

- include: postfix.yml
  when: postfix == True

- name: syslogd flags
  sysrc: key="syslogd_flags" value="{{ syslogd_flags }}"
    state="present"
  notify: restart syslogd

#- name: pf.conf
#  templates: src=pf.conf.j2
#    dest=/etc/pf.conf
#    owner=root
#    group=wheel
#    mode=0644
#    verify='pfctl -nf %s'
#  notify: restart pf
#  when: pf
