---
- include: logwatch.yml
  when: logwatch == "YES"

- include: sshguard.yml
  when: sshguard == "YES"

- name: git package
  pkgng: name=git state=present cached=yes
  when: git == True

- name: bsdstats
  pkgng: name=bsdstats state=present cached=yes

- include: periodic.yml 

- include: rcconf.yml
