---
- name: logwatch package
  pkgng: name=logwatch state=present cached=yes
  tags:
  - packages

- name: logwatch cron job
  cron: name=logwatch
    job=/usr/local/sbin/logwatch.pl
    user=root
    hour="{{ logwatch_hour}}"
    minute=0
    state=present

- name: logwatch conf file
  template: src=logwatch.conf
    dest=/usr/local/etc/logwatch.conf
    owner=root
    group=wheel
    mode=0644

- name: set logwatch mail recipient
  lineinfile: dest=/usr/local/etc/logwatch.conf
    regexp="^MailTo ="
    line="MailTo = {{ periodic_user }}"

