---
# Common settings
- include: hostname.yml
  when: hostname is defined

- include: freebsd.yml
  when: ansible_distribution == 'FreeBSD'

- include: sudoers.yml tags="common,base,sudo"

- include: rsync.yml tags="common,base,packages,rsync"
