---
- name: install openntpd
  pkgng: name=openntpd state=present
  tags:
  - packages

- name: disable ntpd
  service: name=ntpd state=stopped enabled=no

- name: openntpd config
  template: src=ntpd.conf.j2
    dest=/usr/local/etc/ntpd.conf
    owner=root
    group=wheel
    mode=0644
  notify: set time
  notify: restart openntpd

- name: start openntpd
  service: name=openntpd state=started enabled=yes
