---
- name: periodic.conf
  template: src=periodic.conf
    dest=/etc/periodic.conf
    owner=root
    group=wheel
    mode=0755

- name: set periodic mail recipient
  lineinfile: "dest=/etc/aliases
    line='root: {{ periodic_user }}'" #"
  notify: update aliases
