---
- name: pf.conf
  template: src=pf.conf.j2
    dest=/etc/pf.conf
    owner=root
    group=wheel
    mode=0600
    validate='pfctl -vnf %s'
  notify: reload pf

- name: enable pf
  service: name=pf enabled=yes
- name: enable pflog
  service: name=pflog enabled=yes
  
- name: enable pf
  command: pfctl -e
  async: 20
  poll: 1
  ignore_errors: yes

- name: start pf
  service: name=pf state=started
- name: start pflog
  service: name=pflog state=started

- name: ensure rc.d
  file: path=/usr/local/etc/rc.d
    state=directory
    owner=root
    group=wheel
    mode=0755

- name: install pf_reloader
  copy: src=pf_reloader dest=/usr/local/etc/rc.d/rc_reloader
    owner=root
    group=wheel
    mode=0744

- name: enable pf_reloader
  sysrc: key={{item.name}} value={{item.value}} state=present
  with_items:
  - { name: "pf_reloader_enable", value: "YES" }
  - { name: "pf_reloader_flags", value: "reload" }
