---
- name: postfix
  pkgng: name=postfix state=present
  tags:
  - packages

- name: mailer.conf
  template: src=mailer.conf
    dest=/etc/mail/mailer.conf
    owner=root
    group=wheel
    mode=0644

- name: disable sendmail
  service: name=sendmail state=stopped

- name: start postfix
  service: name=postfix state=started
