---
- name: postfix
  pkgng: name=postfix state=present
  tags:
  - packages

- name: postfix | disable sendmail
  sysrc: key="{{item}}"
    value='NO'
    state=present
  with_items:
  - 'sendmail_enable'
  - 'sendmail_submit_enable'
  - 'sendmail_outbound_enable'
  - 'sendmail_msp_queue_enable'

- name: mailer.conf
  template: src=mailer.conf
    dest=/etc/mail/mailer.conf
    owner=root
    group=wheel
    mode=0644

- name: disable sendmail
  service: name=sendmail state=stopped

- name: start postfix
  service: name=postfix state=started enabled=yes
