---
- name: sshd
  service: name=sshd state=started enabled=yes
  tags: sshd

- name: sshd config file
  template: src=sshd_config.j2
    dest=/etc/ssh/sshd_config
    owner=root group=wheel 
    mode=0644
  tags: sshd
  notify: restart sshd

- name: ssh client config file
  template: src=ssh_config.j2
    dest=/etc/ssh/ssh_config
    owner=root group=wheel 
    mode=0644
  tags: sshd
