---
- name: install sshguard
  pkgng: name=sshguard state=present
  tags:
  - packages
  when: not pf

- name: install sshguard-pf
  pkgng: name=sshguard-pf state=present
  when: pf

- name: hosts.allow
  file: path=/etc/hosts.allow
    owner=root
    group=wheel
    mode=0644
    state=file
  when: not pf

- name: whitelist file
  copy: path=/usr/local/etc/sshguard.whitelist
    owner=root
    group=wheel
    mode=0644
    content="{{ sshguard_whitelisted }}"
    #"

- name: sshguard flags
  sysrc: key="{{ item.key }}"
    value="{{ item.value }}"
    state=present
  with_items:
  - { key: 'sshguard_watch_logs', value: "{{ sshguard_watch_logs }}" }
  - { key: 'sshguard_safety_thresh', value: "30" }
  - { key: 'sshguard_pardon_min_interval', value: "21600" }
  - { key: 'sshguard_prescribe_interval', value: "86400" }
  notify: restart sshguard

- name: start sshguard
  service: name=sshguard state=started enabled=yes
