---
- include_vars: portable.yml
  when: ssh_portable

- name: ansible group
  group: name=ansible state=present

- name: add ansible user
  action: user name=ansible 
    shell=/bin/sh 
    group=ansible 
    groups=wheel 
    append=yes

- name: upload ansible key
  authorized_key: user=ansible
    key="{{ lookup('file', '/home/matt/.ssh/ansible_rsa.pub') }}"
    #"
- name: upload root key
  authorized_key: user=root
    key="{{ lookup('file', '/home/matt/.ssh/ansible_rsa.pub') }}"
    #"

- name: sshd config file
  template: src=sshd_config.j2
    dest={{ ssh_conf }}/sshd_config
    owner=root group=wheel 
    mode=0644
  tags: sshd
  notify: restart sshd

- name: ssh client config file
  template: src=ssh_config.j2
    dest={{ ssh_conf }}/ssh_config
    owner=root group=wheel 
    mode=0644
  tags: sshd
